language: c
dist: xenial

addons:
  apt:
    packages:
    - tree
    - cmake
env:
  matrix:
    - TRANSOCKS_OPTIONS="-DENABLE_DEBUG=ON -DLibevent2_USE_STATIC_LIB=ON"
    - TRANSOCKS_OPTIONS="-DENABLE_DEBUG=ON -DLibevent2_USE_STATIC_LIB=OFF"
    - TRANSOCKS_OPTIONS="-DENABLE_DEBUG=OFF -DLibevent2_USE_STATIC_LIB=ON"
    - TRANSOCKS_OPTIONS="-DENABLE_DEBUG=OFF -DLibevent2_USE_STATIC_LIB=OFF"
before_install:
  - LIBEVENT_VER=2.1.11-stable
  - SRCDIR=$PWD
  - echo $SRCDIR
  - curl -O -L https://github.com/libevent/libevent/releases/download/release-${LIBEVENT_VER}/libevent-${LIBEVENT_VER}.tar.gz
  - tar xf libevent-${LIBEVENT_VER}.tar.gz
  - pushd libevent-*
  - ./configure --prefix=$SRCDIR/libevent-install && make && make install
  - tree $SRCDIR/libevent-install
  - popd
script:
  - SRCDIR=$PWD
  - echo $SRCDIR
  - mkdir build
  - pushd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH="$SRCDIR/transocks-wong-bin" -DCMAKE_FIND_ROOT_PATH:PATH=$SRCDIR/libevent-install\;/usr $TRANSOCKS_OPTIONS ..
  - make install
  - tree $SRCDIR/transocks-wong-bin
  - ldd $SRCDIR/transocks-wong-bin/bin/transocks-wong
